import jsPDF from 'jspdf';
import 'jspdf-autotable';

// --- Assets ---
// In a real app, import Base64 logos or fetch them.
// For now, using text/shapes placeholders.

/**
 * Generates a detailed Progress Report PDF
 * @param {Object} student - Student Info { name, level, age }
 * @param {Object} skillsData - Skill Ratings matches the structure used in EvaluationCard
 */
export const generateProgressReport = (student, skillsData) => {
    const doc = new jsPDF();

    // Brand Colors
    const NAVY = [15, 23, 42]; // #0f172a
    const EMERALD = [16, 185, 129]; // #10b981

    // Header Background
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, 210, 40, 'F');

    // Header Text
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text("WILD ROBOT | GYMNASTICS", 15, 20);

    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text("Progress Report", 15, 30);

    // Student Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text(`Student: ${student.name}`, 15, 55);
    doc.text(`Level: ${student.level}`, 15, 62);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 55);

    // Prepare Table Data
    let tableRows = [];

    // skillsData corresponds to the structure:
    // { Floor: [{name: 'Handstand', rating: 4, note: 'Good form'}], Vault: ... }

    Object.keys(skillsData).forEach(apparatus => {
        // Section Header Row
        tableRows.push([{ content: apparatus.toUpperCase(), colSpan: 3, styles: { fillColor: [241, 245, 249], fontStyle: 'bold' } }]);

        skillsData[apparatus].forEach(skill => {
            const stars = "★".repeat(skill.rating) + "☆".repeat(5 - skill.rating);
            tableRows.push([
                skill.name,
                stars,
                skill.note || '-'
            ]);
        });
    });

    // Auto Table
    doc.autoTable({
        startY: 70,
        head: [['Skill', 'Rating', 'Coach Note']],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: EMERALD, textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 40 },
            2: { cellWidth: 'auto' }
        }
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Wild Robot System", 15, pageHeight - 10);

    doc.save(`${student.name.replace(' ', '_')}_Report.pdf`);
};

/**
 * Generates a Gold Certificate for completing a level
 * @param {Object} student 
 */
export const generateCertificate = (student) => {
    const doc = new jsPDF({ orientation: 'landscape' });

    // Decorative Border (Gold)
    doc.setDrawColor(212, 175, 55); // Gold
    doc.setLineWidth(5);
    doc.rect(10, 10, 277, 190);

    // Inner Border (Navy)
    doc.setDrawColor(15, 23, 42); // Navy
    doc.setLineWidth(1);
    doc.rect(15, 15, 267, 180);

    // Title
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(40);
    doc.text("CERTIFICATE OF ACHIEVEMENT", 148.5, 60, { align: 'center' });

    // Body
    doc.setFontSize(20);
    doc.setFont('helvetica', 'normal');
    doc.text("This certifies that", 148.5, 85, { align: 'center' });

    // Name
    doc.setFontSize(50);
    doc.setTextColor(16, 185, 129); // Emerald
    doc.setFont('times', 'bolditalic');
    doc.text(student.name, 148.5, 110, { align: 'center' });

    // Description
    doc.setFontSize(20);
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'normal');
    doc.text(`Has successfully mastered Level: ${student.level}`, 148.5, 140, { align: 'center' });

    // Signature Area
    doc.setLineWidth(0.5);
    doc.line(70, 170, 130, 170); // Line 1
    doc.line(170, 170, 230, 170); // Line 2

    doc.setFontSize(12);
    doc.text("Head Coach", 100, 175, { align: 'center' });
    doc.text("Director", 200, 175, { align: 'center' });

    // Date
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 148.5, 185, { align: 'center' });

    doc.save(`${student.name.replace(' ', '_')}_Certificate.pdf`);
};
